# Introduction


NumPy is the fundamental package for scientific computing with Python. It contains among other things:

a powerful N-dimensional array object
sophisticated (broadcasting) functions
tools for integrating C/C++
useful linear algebra, Fourier transform, and random number capabilities
|

Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined and this allows NumPy to seamlessly and speedily integrate with a wide variety of projects. We are going to explore numpy through a simple example.

# Installation-

Anaconda already includes 100 of the most popular Python packages for datascience and Numpy is ine of them, 
Note that recent versions of Python 3 come with pip, so double check if you have it and if you do, upgrade it before you install NumPy:

- pip install pip --upgrade
- pip --version

Next, you can go https://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy to get your NumPy wheel. After you have downloaded it, navigate to the folder on your pc that stores it through the terminal and install it:

- install "numpy-1.9.2rc1+mkl-cp34-none-win_amd64.whl"
- import numpy
- numpy.__version__

# Array

Arrays
A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

### Creating Arrays-

In [23]:
import numpy as np
x, y, z = np.loadtxt('tial_data.txt',
                    skiprows=1,
                    unpack=True)


In [24]:
np.loadtxt?

In [25]:
x

array([ 0.2536,  0.4839,  0.1292,  0.1781,  0.6253])

In [26]:
y

array([ 0.1008,  0.4536,  0.6875,  0.3049,  0.3486])

In [27]:
z

array([ 0.3857,  0.3561,  0.5929,  0.8928,  0.8791])

In [28]:
wines = np.genfromtxt("winequality-red.csv", delimiter=";", skip_header=1)


In [29]:

a = np.arange(15).reshape(3, 5)


In [30]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [31]:
a.shape

(3, 5)

In [32]:
a.ndim

2

In [33]:
a.dtype.name

'int64'

In [34]:
a.size

15

In [35]:
type(a)

numpy.ndarray

In [36]:
b = np.array([6, 7, 8])

In [37]:
b

array([6, 7, 8])

In [38]:
type(b)


numpy.ndarray

In [39]:
c = np.array( [ [1,2], [3,4] ], dtype=complex )

In [41]:
c

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])


Create a 2-D array whose diagonal equals [1, 2, 3, 4] and 0's elsewhere.

In [42]:
np.diagflat([1, 2, 3, 4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [43]:
X = np.array([[ 0, 1, 2, 3], [ 4, 5, 6, 7], [ 8, 9, 10, 11]])
np.diag(X)

array([ 0,  5, 10])

The function zeros() creates an array full of zeros, the function ones() creates an array full of ones, and the function empty() creates an array whose initial content is random and depends on the state of the memory. By default, the dtype of the created array is float64.

In [44]:
np.zeros( (3,4) )

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [45]:
np.ones( (2,3,4), dtype=np.int16 )

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [46]:
np.empty( (2,3) )

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

To create sequences of numbers, NumPy provides a function analogous to range().

In [47]:
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

In [48]:
np.linspace( 0, 2, 9 )                 # 9 numbers from 0 to 2

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

rndom module helps to create random number arrays

In [49]:
a = np.random.random((2,3))

reshape() will help to change the shape of an array

In [50]:
 b = np.arange(12).reshape(4,3) 

In [51]:
c = np.arange(24).reshape(2,3,4) 

### Basic Operation

In [52]:
 a = np.random.random((2,3))

In [53]:
a.sum()

1.2110274783996551

In [54]:
a.min()

0.039298125727538102

In [55]:
a.max()

0.50034252557741465

In [56]:
a.sum(axis=0)   # sum of each column


array([ 0.15130803,  0.61548215,  0.4442373 ])

In [57]:
a.min(axis=1)  #min of each row

array([ 0.1120099 ,  0.03929813])

In [58]:
b.cumsum(axis=1)  # cumulative sum along each row

array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21],
       [ 9, 19, 30]])

### Universal Functions

NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal functions”(ufunc). Within NumPy, these functions operate elementwise on an array, producing an array as output.

In [59]:
np.exp(a)

array([[ 1.11852394,  1.6492861 ,  1.37425156],
       [ 1.04008051,  1.12203008,  1.13465432]])

In [60]:
np.sqrt(a)

array([[ 0.33467881,  0.70734894,  0.56383443],
       [ 0.19823755,  0.33932229,  0.35542656]])

In [61]:
C = np.array([2., -1., 4.])
B = np.arange(3)
np.add(B, C)

array([ 2.,  0.,  6.])

### Stacking together different arrays

Several arrays can be stacked together along different axes:

In [62]:
a = np.floor(10*np.random.random((2,2)))

In [63]:
b = np.floor(10*np.random.random((2,2)))

In [64]:
np.vstack((a,b))

array([[ 0.,  9.],
       [ 7.,  8.],
       [ 5.,  8.],
       [ 5.,  5.]])

In [65]:
np.hstack((a,b))

array([[ 0.,  9.,  5.,  8.],
       [ 7.,  8.,  5.,  5.]])

The function column_stack stacks 1D arrays as columns into a 2D array. It is equivalent to vstack only for 1D arrays:

In [66]:
from numpy import newaxis

In [67]:
np.column_stack((a,b))  

array([[ 0.,  9.,  5.,  8.],
       [ 7.,  8.,  5.,  5.]])

In [68]:
a = np.array([4.,2.])
b = np.array([2.,8.])

In [69]:
a[:,newaxis] 

array([[ 4.],
       [ 2.]])

In [70]:
np.column_stack((a[:,newaxis],b[:,newaxis]))

array([[ 4.,  2.],
       [ 2.,  8.]])

In [71]:
np.vstack((a[:,newaxis],b[:,newaxis]))

array([[ 4.],
       [ 2.],
       [ 2.],
       [ 8.]])

### Splitting one array into several smaller ones

In [72]:
a = np.floor(10*np.random.random((2,12)))

In [73]:
a

array([[ 5.,  6.,  7.,  0.,  7.,  5.,  9.,  2.,  9.,  8.,  8.,  6.],
       [ 6.,  2.,  2.,  3.,  3.,  8.,  1.,  6.,  2.,  0.,  4.,  9.]])

In [75]:
np.hsplit(a,3) #split into 3

[array([[ 5.,  6.,  7.,  0.],
        [ 6.,  2.,  2.,  3.]]), array([[ 7.,  5.,  9.,  2.],
        [ 3.,  8.,  1.,  6.]]), array([[ 9.,  8.,  8.,  6.],
        [ 2.,  0.,  4.,  9.]])]

In [76]:
np.hsplit(a,(3,4))   # Split a after the third and the fourth column

[array([[ 5.,  6.,  7.],
        [ 6.,  2.,  2.]]), array([[ 0.],
        [ 3.]]), array([[ 7.,  5.,  9.,  2.,  9.,  8.,  8.,  6.],
        [ 3.,  8.,  1.,  6.,  2.,  0.,  4.,  9.]])]

#### View Or shallow Copy

The view method creates a new array object that looks at the same data.

In [77]:
c = a.view()

In [78]:
c is a

False

In [79]:
 c.base is a                        # c is a view of the data owned by a

True

In [80]:
c[0,4] = 1234                      # a's data changes

In [81]:
a

array([[  5.00000000e+00,   6.00000000e+00,   7.00000000e+00,
          0.00000000e+00,   1.23400000e+03,   5.00000000e+00,
          9.00000000e+00,   2.00000000e+00,   9.00000000e+00,
          8.00000000e+00,   8.00000000e+00,   6.00000000e+00],
       [  6.00000000e+00,   2.00000000e+00,   2.00000000e+00,
          3.00000000e+00,   3.00000000e+00,   8.00000000e+00,
          1.00000000e+00,   6.00000000e+00,   2.00000000e+00,
          0.00000000e+00,   4.00000000e+00,   9.00000000e+00]])

#### Deep Copy

In [82]:
d = a.copy()                          # a new array object with new data is created

In [83]:
d is a

False

In [84]:
d.base is a  # d doesn't share anything with a

False

In [85]:
d[0,0] = 9999

In [86]:
a

array([[  5.00000000e+00,   6.00000000e+00,   7.00000000e+00,
          0.00000000e+00,   1.23400000e+03,   5.00000000e+00,
          9.00000000e+00,   2.00000000e+00,   9.00000000e+00,
          8.00000000e+00,   8.00000000e+00,   6.00000000e+00],
       [  6.00000000e+00,   2.00000000e+00,   2.00000000e+00,
          3.00000000e+00,   3.00000000e+00,   8.00000000e+00,
          1.00000000e+00,   6.00000000e+00,   2.00000000e+00,
          0.00000000e+00,   4.00000000e+00,   9.00000000e+00]])

#### Indexing with Boolean Arrays

In [87]:
a = np.arange(12).reshape(3,4)

In [88]:
b = a > 4

In [89]:
b 

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]], dtype=bool)

In [90]:
a[b] 

array([ 5,  6,  7,  8,  9, 10, 11])

This property can be very useful in assignments:

In [91]:
a[b] = 0                                   # All elements of 'a' higher than 4 become 0

### Linear Algebra

In [92]:
a = np.array([[1.0, 2.0], [3.0, 4.0]])

In [93]:
a

array([[ 1.,  2.],
       [ 3.,  4.]])

In [94]:
a.transpose()

array([[ 1.,  3.],
       [ 2.,  4.]])

In [95]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [96]:
u = np.eye(6) 

In [97]:
u

array([[ 1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.]])

In [98]:
j = np.array([[0.0, -1.0], [1.0, 0.0]])

In [99]:
np.dot (j, j) # matrix product

array([[-1.,  0.],
       [ 0., -1.]])

### Shape Manipulation¶

In [100]:
a = np.floor(10*np.random.random((3,4)))

In [101]:
a

array([[ 7.,  2.,  8.,  9.],
       [ 9.,  6.,  5.,  5.],
       [ 9.,  3.,  5.,  2.]])

In [102]:
a.shape

(3, 4)

The shape of an array can be changed with various commands. Note that the following three commands all return a modified array, but do not change the original array:

In [103]:
a.ravel()  # returns the array, flattened

array([ 7.,  2.,  8.,  9.,  9.,  6.,  5.,  5.,  9.,  3.,  5.,  2.])

In [104]:
 a.reshape(6,2) 

array([[ 7.,  2.],
       [ 8.,  9.],
       [ 9.,  6.],
       [ 5.,  5.],
       [ 9.,  3.],
       [ 5.,  2.]])

In [105]:
a.T  # returns the array, transposed

array([[ 7.,  9.,  9.],
       [ 2.,  6.,  3.],
       [ 8.,  5.,  5.],
       [ 9.,  5.,  2.]])

In [106]:
a.T.shape

(4, 3)

In [107]:
a.shape

(3, 4)

The reshape function returns its argument with a modified shape, whereas the ndarray.resize method modifies the array itself:

In [108]:
a.resize((2,6))

In [109]:
a

array([[ 7.,  2.,  8.,  9.,  9.,  6.],
       [ 5.,  5.,  9.,  3.,  5.,  2.]])

### Broadcasting


roadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:



In [110]:


# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

# Now y is the following
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


This works; however when the matrix x is very large, computing an explicit loop in Python could be slow. Note that adding the vector v to each row of the matrix x is equivalent to forming a matrix vv by stacking multiple copies of v vertically, then performing elementwise summation of x and vv. We could implement this approach like this:



In [111]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))   # Stack 4 copies of v on top of each other
print(vv)                 # Prints "[[1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]]"
y = x + vv  # Add x and vv elementwise
print(y)  # Prints "[[ 2  2  4
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [112]:
a= np.arange(15)

In [113]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [114]:
a[0:8]=100

In [115]:
a

array([100, 100, 100, 100, 100, 100, 100, 100,   8,   9,  10,  11,  12,
        13,  14])

Numpy broadcasting allows us to perform this computation without actually creating multiple copies of v. Consider this version, using broadcasting:



In [116]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)  # Prints "[[ 2  2  4]
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


for more detials donot forget to refer- http://scipy.github.io/old-wiki/pages/EricsBroadcastingDoc

### Datatypes

For more details please refer the link- https://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html

NumPy has several different data types, which mostly map to Python data types, like float, and str. You can find a full listing of NumPy data types here, but here are a few important ones:

- float -- numeric floating point data.
- int -- integer data.
- string -- character data.
- object -- Python objects.
Data types additionally end with a suffix that indicates how many bits of memory they take up. So int32 is a 32 bit integer data type, and float64 is a 64 bit float data type.

In [117]:
x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)         # Prints "int64"


int64


In [118]:
x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype)                         # Prints "int64"

int64


### Converting Data Types

You can use the numpy.ndarray.astype method to convert an array to a different type. The method will actually copy the array, and return a new array with the specified data type.

In [119]:
wines

array([[  7.4  ,   0.7  ,   0.   , ...,   0.56 ,   9.4  ,   5.   ],
       [  7.8  ,   0.88 ,   0.   , ...,   0.68 ,   9.8  ,   5.   ],
       [  7.8  ,   0.76 ,   0.04 , ...,   0.65 ,   9.8  ,   5.   ],
       ..., 
       [  6.3  ,   0.51 ,   0.13 , ...,   0.75 ,  11.   ,   6.   ],
       [  5.9  ,   0.645,   0.12 , ...,   0.71 ,  10.2  ,   5.   ],
       [  6.   ,   0.31 ,   0.47 , ...,   0.66 ,  11.   ,   6.   ]])

For instance, we can convert wines to the int data type:



In [120]:
wines.astype(int)


array([[ 7,  0,  0, ...,  0,  9,  5],
       [ 7,  0,  0, ...,  0,  9,  5],
       [ 7,  0,  0, ...,  0,  9,  5],
       ..., 
       [ 6,  0,  0, ...,  0, 11,  6],
       [ 5,  0,  0, ...,  0, 10,  5],
       [ 6,  0,  0, ...,  0, 11,  6]])